name = "austere"
description = "A minimal theme for Zola with a focus on writing."
license = "MIT"
homepage = "https://github.com/austere-theme-zola"
min_version = "0.17.0"
demo = ""

[author]
name = "tomwrw"
homepage = "https://www.tomwrw.co.uk"
